## GENERAL ##
PM_SIGNOFF = "I am a Bot. If you have any queries, please contact [Demigodrick](/u/demigodrick@lemmy.zip) or [Sami](/u/sami@lemmy.zip). Beep Boop."
AUTOPOST_HELP = "If you need any further help getting this working, please contact [Demigodrick](/u/demigodrick@lemmy.zip)."
SUB_ERROR = "Please message [Demigodrick](/u/demigodrick@lemmy.zip) or [Sami](/u/sami@lemmy.zip) directly to let them know, and they'll sort it out for you."
EMAIL_SUBJECT = "Thanks for signing up to Lemmy.zip!"
BOT_NAME = "ZippyBot"
FEEDBACK_URL = "https://feedback.lemmy.zip"

## REPORTS ##

REPORT_NOT_LOCAL_NOT_URGENT = "Thank you for submitting your report. \n\n We take each report seriously and ensure it undergoes a thorough manual review. Please note, since the content you reported is not hosted directly on Lemmy.zip, our ability to take action might be limited if it doesn't violate Lemmy.zip's [Code of Conduct](https://legal.lemmy.zip/docs/code_of_conduct/). \n Responsibility for moderation in such cases typically falls to the moderators and admins of the specific local instance where the content is posted.\n\n Your vigilance in helping maintain a safe and respectful community is greatly appreciated."    
REPORT_LOCAL_NOT_URGENT = "Thank you for submitting your report. \n\n We value your effort in helping us maintain a safe and respectful community on Lemmy.zip. Every report is taken seriously and undergoes a thorough manual review by our team.\n We assure you that appropriate actions will be taken based on our [Code of Conduct](https://legal.lemmy.zip/docs/code_of_conduct/).\n\n Your vigilance in helping maintain a safe and respectful community is greatly appreciated."

POST_REPORT_NOT_LOCAL_URGENT = "Thank you for submitting your report. \n\n We take each report seriously and ensure it undergoes a thorough manual review. Please note, since the content you reported is not hosted directly on Lemmy.zip, our ability to take action might be limited if it doesn't violate Lemmy.zip's [Code of Conduct](https://legal.lemmy.zip/docs/code_of_conduct/). \n Responsibility for moderation in such cases typically falls to the moderators and admins of the specific local instance where the content is posted.\n\n However, if you believe the content in question is illegal or demands urgent attention, we urge you to reply to this message immediately with `#urgent -p -\{report_id}\` (copy and paste only this text into the reply box).\n\n This will alert our administration team, who will take immediate action as necessary. Your vigilance in helping maintain a safe and respectful community is greatly appreciated."
POST_REPORT_LOCAL_URGENT = "Thank you for submitting your report. \n\n We value your effort in helping us maintain a safe and respectful community on Lemmy.zip. Every report is taken seriously and undergoes a thorough manual review by our team.\n We assure you that appropriate actions will be taken based on our [Code of Conduct](https://legal.lemmy.zip/docs/code_of_conduct/).\n\n In instances where you believe the content is illegal and/or requires urgent intervention (such as CSAM or a threat to life), we urge you to reply to this message immediately with `#urgent -p -\{report_id}\` (copy and paste only this text into the reply box). \n\n This will alert our administration team who will take immediate action as necessary. Your vigilance in helping maintain a safe and respectful community is greatly appreciated."
COMMENT_REPORT_NOT_LOCAL_URGENT = "Thank you for submitting your report. \n\n We take each report seriously and ensure it undergoes a thorough manual review. Please note, since the content you reported is not hosted directly on Lemmy.zip, our ability to take action might be limited if it doesn't violate Lemmy.zip's [Code of Conduct](https://legal.lemmy.zip/docs/code_of_conduct/). \n Responsibility for moderation in such cases typically falls to the moderators and admins of the specific local instance where the content is posted.\n\n However, if you believe the content in question is illegal or demands urgent attention, we urge you to reply to this message immediately with `#urgent -c -\{report_id}\` (copy and paste only this text into the reply box).\n\n This will alert our administration team, who will take immediate action as necessary. Your vigilance in helping maintain a safe and respectful community is greatly appreciated."
COMMENT_REPORT_LOCAL_URGENT = "Thank you for submitting your report. \n\n We value your effort in helping us maintain a safe and respectful community on Lemmy.zip. Every report is taken seriously and undergoes a thorough manual review by our team.\n We assure you that appropriate actions will be taken based on our [Code of Conduct](https://legal.lemmy.zip/docs/code_of_conduct/).\n\n In instances where you believe the content is illegal and/or requires urgent intervention (such as CSAM or a threat to life), we urge you to reply to this message immediately with `#urgent -c -\{report_id}\` (copy and paste only this text into the reply box). \n\n This will alert our administration team who will take immediate action as necessary. Your vigilance in helping maintain a safe and respectful community is greatly appreciated."